# -*- coding: utf-8 -*-
"""Mesh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HMUQeTcNtXySy3CYzsg1DJPbTAsrV2b
"""


from PIL import Image, ImageDraw, ImageFilter, ImageChops
from PIL.ImageTransform import MeshTransform
import numpy as np
import random

import sys

from generative.utilities import make_mask, make_transparent, draw_mesh
from generative.transforms import create_randomized_aligned_mesh


IN_COLAB = 'google.colab' in sys.modules
test_mesh = False


use_mask = True
layers = 1
files = 1
radius = 5

source_folder = '/content/' if IN_COLAB else 'input/'

if test_mesh:
  image_path = 'grid_image.png'
else:
  image_path = 'Rhythms_Circle_DataReferenceSet_1982_2.png'
##  image_path = 'abstract_artwork_with_neon1.png'
##  image_path = 'rhythms_entropic_heavens_waves_continue_v10.png'
##  image_path = 'myanmar_tm5_2004349_lrg.jpg'
##  image_path =  'PXL_20240906_152258909.jpg'

def invert(image):
# Create a mask with a white circle on a black background
  mask = Image.new('L', image.size, 0)
  draw = ImageDraw.Draw(mask)

  # Define the circle's center and radius
  center_x = image.width // 2
  center_y = image.height // 2
  radius = min(center_x, center_y) // 2  # Example: half of the smaller dimension

  # Draw a white circle on the mask
  draw.ellipse((center_x - radius, center_y - radius, center_x + radius, center_y + radius), fill=255)

  # Invert the circular region of the image
  inverted_image = ImageChops.invert(image)
  image.paste(inverted_image, mask=mask)
  
# return the blurred image
  return(image)
  

def blur(image, x, y, width, height, radius, fill, outline, outline_width):

  # Apply Gaussian Blur

  mask = Image.new('L', (width, height), 0)

# Create a draw object for the mask
  draw = ImageDraw.Draw(mask)

  # Define the bounding box for the ellipse
  bounding_box = (0, 0, width, height)  # Adjust as needed

  # Draw the ellipse on the mask (white color fills the ellipse)
  draw.ellipse(bounding_box, fill=255)

  # Apply the mask to the image
  # image.putalpha(mask)
  
  cropped = image.crop((x,y,x+width,y+height))

  blurred_image = cropped.filter(ImageFilter.GaussianBlur(radius))
  overlay = Image.new('RGBA', cropped.size, (0,0,0,0))
  odraw = ImageDraw.Draw(overlay)    
  odraw.ellipse(bounding_box, fill, outline, outline_width)
  blurred_image = Image.alpha_composite(blurred_image, overlay)

  filename = f"output/blurred.png"
  overlay.save(filename)
  overlay.show(filename)

  image.paste(blurred_image,(dx,dy), mask)



# return the blurred image
  return(image)


# Open the image
input_path = f"input/{image_path}"

for file in range(0,files):
  image = Image.open(input_path)
  image = image.convert('RGBA')

  im = make_transparent(image, 128)
  for _ in range(0, layers):
    # Apply the mesh transform
    #mesh = make_mesh(3,im)
    mesh = create_randomized_aligned_mesh(3,2,im.width,im.height)
    # Create a new image with the mesh
    out = im.transform(im.size, MeshTransform(mesh))
    mask = out if use_mask else None
    #draw the transformed image on the original using a mask
    image.paste(out, None, mask)

    width = int(image.width/3)
    height = int(image.height/3)
    dx = 0
    dy = 0
    bounding_box=(0,0,width,height)
    out = blur(image, 0, 0, width, height, 5, (0,255,0,128), (0,0,0,255), 10)
    image.paste(out, (dx,dy), out)

  if test_mesh:
    draw_mesh(mesh, image)
    
  filename = f"output/mesh_image{file}.png"
  image.save(filename)
  image.show(filename)

