# -*- coding: utf-8 -*-
"""Mesh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HMUQeTcNtXySy3CYzsg1DJPbTAsrV2b
"""


from PIL import Image, ImageDraw, ImageFilter, ImageChops
from PIL.ImageTransform import MeshTransform
import numpy as np
import random

import sys

from generative.utilities import make_mask, make_transparent
from generative.transforms import create_randomized_aligned_mesh


IN_COLAB = 'google.colab' in sys.modules
test_mesh = False


use_mask = True
layers = 1
files = 1
radius = 5

folder = '/content/' if IN_COLAB else './'

if test_mesh:
  image_path = 'grid_image.png'
else:
  image_path = 'Rhythms_Circle_DataReferenceSet_1982_2.png'
##  image_path = 'abstract_artwork_with_neon1.png'
##  image_path = 'rhythms_entropic_heavens_waves_continue_v10.png'
##  image_path = 'myanmar_tm5_2004349_lrg.jpg'
##  image_path =  'PXL_20240906_152258909.jpg'

def invert(image):
# Create a mask with a white circle on a black background
  mask = Image.new('L', image.size, 0)
  draw = ImageDraw.Draw(mask)

  # Define the circle's center and radius
  center_x = image.width // 2
  center_y = image.height // 2
  radius = min(center_x, center_y) // 2  # Example: half of the smaller dimension

  # Draw a white circle on the mask
  draw.ellipse((center_x - radius, center_y - radius, center_x + radius, center_y + radius), fill=255)

  # Invert the circular region of the image
  inverted_image = ImageChops.invert(image)
  image.paste(inverted_image, mask=mask)

  blurred_image.paste(cropped,box, mask)
  
# return the blurred image
  return(blurred_image)
  

def blur(image, x, y, width, height, radius, dx, dy):

  # Apply Gaussian Blur

  width = int(image.width/3)
  height = int(image.height/3)# Create a new image for the mask with the same dimensions and a black background

  mask = Image.new('L', (width, height), 0)

  # Create a draw object for the mask
  draw = ImageDraw.Draw(mask)

  # Define the bounding box for the ellipse
  bounding_box = (0, 0, width, height)  # Adjust as needed

  # Draw the ellipse on the mask (white color fills the ellipse)
  draw.ellipse(bounding_box, fill=255)

  # Apply the mask to the image
##  image.putalpha(mask)
  
  cropped = image.crop((x,y,x+width,y+height))
  blurred_image = cropped.filter(ImageFilter.GaussianBlur(radius))

  box = (x,y)
  image.paste(cropped,box, mask)
  
# return the blurred image
  return(image)


# Open the image
image = Image.open(image_path)
im = make_transparent(image, 128)

for file in range(files):
  image = Image.open(image_path)
  im = make_transparent(image, 128)
  for _ in range(layers):
    # Apply the mesh transform
    #mesh = make_mesh(3,im)
    mesh = create_randomized_aligned_mesh(3,2,im.width,im.height)
    # Create a new image with the mesh
    out = im.transform(im.size, MeshTransform(mesh))
    mask = out if use_mask else None
    #draw the transformed image on the original using a mask
    image.paste(out, None, mask)
    image = blur(image, 0, 0, image.width/3, image.height/3, 5, 0, 0)

  if test_mesh:
    draw_mesh(mesh, image)
    
  filename = f"{folder}mesh_image{file}.png"
  image.save(filename)
  image.show(filename)

