'''

CONSTANTS

'''

import datetime

GOLDEN_RATIO = 1.61803398875

CREATE_PDF = True
SHOW_PDF = True
SHOW_IMAGE = True

MAX_LAYERS = 2
SHAPES = 2**7

FILES = 1
RADIUS = 5
PROB_DO_TRANSFORM = 1
PROB_SHAPE_DESTINATION_EQUALS_SOURCE = 1
SHAPES = 2**8

EPS = 20
MIN_SAMPLES = 64

ACCENT_COLOR_PERCENTAGE = .02

MIN_WIDTH_PERCENTAGE = .01
MIN_HEIGHT_PERCENTAGE = .02
MAX_WIDTH_PERCENTAGE = .1/GOLDEN_RATIO
MAX_HEIGHT_PERCENTAGE = .2

MIN_DX_PERCENTAGE = - .1
MIN_DY_PERCENTAGE = - .1
MAX_DX_PERCENTAGE = .6
MAX_DY_PERCENTAGE = .6

MAX_FILL_ALPHA = 128
MIN_FILL_ALPHA = 32
MAX_FILL_RED = 255
MIN_FILL_RED = 192
MAX_FILL_GREEN = 255
MIN_FILL_GREEN = 128
MAX_FILL_BLUE = 64
MIN_FILL_BLUE = 32

MAX_ACCENT_ALPHA = 212
MIN_ACCENT_ALPHA = 192
MAX_ACCENT_RED = 255
MIN_ACCENT_RED = 192
MAX_ACCENT_GREEN = 16
MIN_ACCENT_GREEN = 0
MAX_ACCENT_BLUE = 16
MIN_ACCENT_BLUE = 0

MAX_OUTLINE_ALPHA = 255
MIN_OUTLINE_ALPHA = 128
MAX_OUTLINE_RED = 255
MIN_OUTLINE_RED = 0
MAX_OUTLINE_GREEN = 255
MIN_OUTLINE_GREEN = 0
MAX_OUTLINE_BLUE = 255
MIN_OUTLINE_BLUE = 0

INPUT_DIR = 'input'
OUTPUT_DIR = 'output'
IMAGE_NAME = 'Rhythms_Circle_DataReferenceSet_1982_2'
IMAGE_EXT = '.png'
IMAGE_DATE = datetime.datetime.now().strftime('%Y%m%d')